### PR TITLE
Update to 23.08beta

### PR DESCRIPTION
**Pull request by alatiera**

### CODE REVIEW

**Comment by alatiera** [comment]
This is a PR mostly for visibility, need to create new branches for `beta` and `branch//23.08`

**Review by bilelmoussaoui — APPROVED** [review]

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by Erick555** [comment]
There is still no 23.08beta runtime release on flathub-beta. Since llvm 15 is EOL I'll prefer to leave it and adopt the changes for [llvm 16](https://github.com/flathub/flathub/pull/4117) instead.

**Comment by alatiera** [comment]
The build is tagged, we are waiting on a working token to push it. 

https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/jobs/4193310887

Given that llvm16 doesn't have a repo yet and all the apps are still using llvm15 I'd like to see this merged and let apps port on their own.

**Comment by Erick555** [comment]
There won't be working token until bart returns at end of week and he can merge llvm16 at same time. Currently I don't plan to make llvm15 for 23.08 final release (it would be two major releases behind at that time) so for apps it may be easier to update llvm during beta phase than use old llvm during whole beta and update it for stable.

**Comment by Erick555** [comment]
llvm16 is ready, waiting for runtime release: https://github.com/flathub/org.freedesktop.Sdk.Extension.llvm16/pull/2

**Comment by orowith2os** [comment]
> llvm16 is ready, waiting for runtime release

Why not publish right now for 22.08? That runtime is still supported, and 21.08 is still supported but a bit old.

**Comment by Erick555** [comment]
llvm16 is available for 22.08 since yesterday:
```
flatpak remote-info flathub org.freedesktop.Sdk.Extension.llvm16
        ID: org.freedesktop.Sdk.Extension.llvm16
       Ref: runtime/org.freedesktop.Sdk.Extension.llvm16/x86_64/22.08
      Arch: x86_64
    Branch: 22.08
Collection: org.flathub.Stable
  Download: 114.3 MB
 Installed: 434.2 MB

    Commit: fc30be74eadd5115fe7ce5429699f50a12f512a3074141326600180a9c939278
   Subject: Update to llvm 16.0.2 (b2975d51)
      Date: 2023-05-04 18:58:12 +0000
```
Linked PR and this one here are about 23.08beta runtime which is still unavailable on flathub.

**Comment by orowith2os** [comment]
OH sorry, I thought the PR you linked was for the flathub/flathub repo, my bad.

**Comment by Erick555** [comment]
Closing in favor of https://github.com/flathub/org.freedesktop.Sdk.Extension.llvm16/pull/5 (although merging anything using fsdk beta is impossible without admin intervention)

**Pull request closed without merging**
